GET {{host}}menu
Authorization: Bearer {{auth_token}}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});

client.test("Request is array", function() {
  client.assert(Array.isArray(response.body), "Request is not array.");
});
%}
